personal:
  name: Davide Pucci
  phone: +39 3298580201
  email: posta@davidepucci.it
  birth_date: 21 Settembre 1995
  address: Via Rocca Sinibalda 10
  city: Roma
  country: Italia
  nationality: Italiano
  image: profile.png
  url_personal: https://davidepucci.it
  url_github: https://github.com/streambinder
  url_github_abbr: github.com/streambinder
  url_linkedin: https://linkedin.com/in/davide-pucci
  url_linkedin_abbr: linkedin.com/in/davide-pucci

work:
  label: Esperienze lavorative
  entries:
    - role: Consulente Sviluppatore
      company: Kubique S.p.A.
      from: 12/2018
      to: 08/2019
      description: >
        Ho sviluppato strumenti software per l'ecosistema dell'open banking utilizzando lo stack Java EE stack e la programmazione orientata agli aspetti.
    - role: Co-fondatore e CTO
      company: Cellula S.r.l.
      from: 07/2016
      to: 12/2018
      description: >
        Ho sviluppato web-applications e amministrato le infrastrutture e i servizi destinati ai clienti.
    - role: Sviluppatore / Ingegnere DevOps
      company: I-node S.r.l.
      from: 10/2015
      to: 12/2018
      description: >
        Ho sviluppato diversi progetti e strumenti per realizzarne il rilascio automatico.
    - role: Amministratore di sistemi
      company: I-node S.r.l.
      from: 07/2014
      to: 12/2018
      description: >
        Ho realizzato ed amministrato infrastrutture di rete complesse.
        Mi sono interfacciato con clienti e terze parti per offrire supporto Tier 1/2.

education:
  school:
    label: Formazione
    entries:
      - program: Laurea magistrale in Sicurezza e Ingegneria delle Reti
        school: Science Park, Università di Amsterdam
        date: 2020
      - program: Laurea triennale in Informatica
        school:  La Sapienza, Università di Roma
        date: 2019
      - program: Diploma di liceo scientifico
        school: L.S.S. Amedeo Avogadro
        date: 2014
  research:
    label: Ricerca
    entries:
      - title: "Agnostic embedding of digital signatures"
        researchers:
          - Sean Liao
        date: 2020
      - title: "Audio Steganography: a Deep Learning Approach"
        researchers:
          - Philippe Partarrieu
        date: 2020
      - title: BGP Flow-Spec for distributed micro-segmentation
        date: 2020
      - title: "REVCON: Reverse Network Reconnaissance"
        researchers:
          - Paul Dunn
          - Philipp Mieden
          - Axel Koolhaas
        date: 2019

projects:
  label: Progetti
  entries:
    - name: MoltenMotherBoard
      members:
        - Marco Panunzio
        - Giovanni Santini
      description: >
        Ho sviluppato sistemi Android personalizzati sotto il nome di MoltenMotherBoard.
        Ho raggiunto il ruolo di manutentore ufficiale del dispositivo LG Optimus 4X HD nel team CyanogenMod.
      from: 2012
      to: 2014

skills:
  label: Abilità
  networking:
    label: Abilità in rete/sistemi
    entries:
      - category: Hosting web
        entries:
          - Apache
          - Nginx
          - IIS
          - ISPConfig
          - Plesk
      - category: Hosting email
        entries:
          - Postfix
          - Courier
          - Dovecot
          - Zimbra
          - Roundcube
      - category: Hosting file e ACL
        entries:
          - Samba
          - NFSv4
          - Kerberos
          - VSFTP
          - FTP
      - category: DBMS
        entries:
          - MySQL/MariaDB
          - PostgreSQL
          - LightDB
          - OrientDB
      - category: Monitoraggio
        entries:
          - Nagios
          - Icinga
          - NagiosQL
          - Cacti
          - Netdata
      - category: Backup
        entries:
          - Bacula
          - Veeam
          - Restic
      - category: Automazione di sviluppo
        entries:
          - Make
          - Maven
          - Gradle
          - Zeus
      - category: Virtualizzazione
        entries:
          - VMware vSphere
          - VirtualBox
          - Vagrant
          - Docker
          - Xen
          - LXC
      - category: Controllo versione
        entries:
          - Git
          - SVN
      - category: Piattaforme cloud
        entries:
          - OwnCloud
          - NextCloud
      - category: Antivirus
        entries:
          - Sophos Enterprise Console
          - Sophos Endpoint Antivirus
          - G Data
      - category: Rete
        entries:
          - FRRouting
          - Bird
          - iptables
          - open/strong/libreSwan
          - OpenVPN
          - GateProtect
      - category: Routing
        entries:
          - BGP
          - OSPF
          - RIP
          - MPLS
          - EVPN
      - category: Sistemi operativi
        entries:
          - Linux
          - Android
          - Windows
          - Windows Server
  coding:
    label: Abilità in sviluppo
    entries:
      - category: Base
        entries:
          - Ruby
          - SQL
      - category: Intermedio
        entries:
          - C
          - PHP
          - LaTeX
          - Java/TypeScript
          - ASM MIPS
      - category: Avanzato
        entries:
          - Java
          - Python
          - Bash
          - Go
      - category: Frameworks
        entries:
          - Laravel
          - Spring Boot
          - Angular/Ionic
          - Flask

languages:
  label: Lingue
  entries:
    - name: Italiano
      proficiency: Madrelingua
    - name: Inglese
      proficiency: B1 - certificazione TOEFL

misc:
  footnote: Autorizzo il trattamento dei miei dati personali ai sensi della legge sulla privacy 196/03 e successive modifiche e integrazioni
  language: italian
